version: "{build}"
image: Ubuntu2004

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
    - master

nuget:
  disable_publish_on_pr: true

build_script:
  - git clean --ffxd
  - dotnet restore
  - dotnet build
  - dotnet pack ./src/ManageRates.sln -c Release -o ./artifacts

test: off
artifacts:
  - path: .\artifacts\*.nupkg
    name: NuGet
