image: Ubuntu2004

branches:
  only:
    - master

nuget:
  disable_publish_on_pr: true

build_script:
  - git clean --ffxd
  - dotnet restore ./src
  - dotnet build ./src -c Release
  - dotnet test ./src -c Release
  - dotnet pack ./src -c Release -o ./artifacts

test: off
artifacts:
  - path: ./artifacts/*.nupkg
    name: NuGet
