image: Ubuntu2004

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
    - master

nuget:
  disable_publish_on_pr: true

build_script:
  - git clean -ffxd
  - dotnet restore ./src
  - dotnet build ./src -c Release --no-restore
  - dotnet test ./src -c Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput='../../../artifacts/'
  - dotnet pack ./src -c Release --no-build --include-symbols -o ./artifacts /p:VersionPrefix=$APPVEYOR_BUILD_VERSION
  - bash <(curl -s https://codecov.io/bash)

test: off
artifacts:
  - path: ./artifacts/*.nupkg
    name: NuGet
  - path: ./artifacts/*.xml
    name: CodeCoverage